#!/usr/bin/env sh
command -v realpath >/dev/null 2>&1 || realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
PROJECTFILE="$(realpath "$SCRIPTPATH/cabal.project")"
exec cabal -v0 --project-file="$PROJECTFILE" v2-run "exe:gen-opencl-packet" -- "$@"
